[config]
model = "gpt-4o-mini"
fallback_models = ["gpt-4o-mini"]
max_model_tokens = 32000
large_patch_policy = "clip"
patch_extension_skip_types = [".md", ".txt", ".json", ".parquet", ".csv", ".properties"]

[pr_reviewer]
require_focused_review = true
require_score_review = true
require_security_review = true
num_code_suggestions = 0

[pr_description]
publish_labels = false
add_custom_labels = false

[github_action_config]
auto_review = true
auto_describe = true
auto_improve = false
pr_actions = ["opened", "reopened", "ready_for_review", "synchronize"]
