# .github/workflows/pr-agent.yml
name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  issue_comment:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      checks: write
    name: Run pr agent on every pull request
    steps:
      - name: PR Agent action step
        id: pragent
        uses: the-pr-agent/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "false"
          github_action_config.pr_actions: '["opened", "synchronize", "reopened", "ready_for_review"]'
          pr_description.publish_description_as_comment: "true"
          config.model: "gpt-4o-mini"
          config.fallback_models: '["gpt-4o-mini"]'
          config.max_model_tokens: "32000"
          config.large_patch_policy: "clip"